In [136]:
import usaddress
import pandas as pd
import numpy as np
import collections

In [139]:

df = pd.read_excel('Test Data Texas.xlsx',sheet_name=1)

In [144]:
df

,Qty,Sales Price,Amount,Tax Amount,Taxable Amount,Class,Location,Shipping Address,Shipping Zip,State
0,1.0,28.00,28.00,0.00,28.00,Website:Facebook,WEBSITE,"Robin Romans,7005 Rain Creek Pkwy,Austin, Texa...",78759,TX
1,1.0,18.99,18.99,0.00,18.99,Website:Facebook,WEBSITE,"Robin Romans,7005 Rain Creek Pkwy,Austin, Texa...",78759,TX
2,1.0,9.24,9.24,6.21,9.24,Website:Facebook,WEBSITE,"Robin Romans,7005 Rain Creek Pkwy,Austin, Texa...",78759,TX
3,1.0,40.99,40.99,0.00,40.99,Website,WEBSITE,"Tom Mackowski,6905 Nottoway Lane,Lumberton Tex...",77657,TX
4,1.0,40.99,40.99,0.00,40.99,Website,WEBSITE,"Tom Mackowski,6905 Nottoway Lane,Lumberton Tex...",77657,TX
...,...,...,...,...,...,...,...,...,...,...
1024,NaN,NaN,-25.35,0.00,0.00,Online Retail,Wholesale - TX,NaN,75039,TX
1025,-2.0,47.00,-94.00,0.00,0.00,Online Retail,Wholesale - TX,NaN,75039,TX
1026,-1.0,45.00,-45.00,0.00,0.00,Online Retail,Wholesale - TX,NaN,75039,TX
1027,NaN,NaN,-25.70,0.00,0.00,Online Retail,Wholesale - TX,NaN,75039,TX
1028,-2.0,25.00,-50.00,0.00,0.00,Wholesale,Wholesale - TX,0,76182,TX

In [141]:
l = df['Shipping Address'].to_numpy()
j = []

for i,k in enumerate(l):
    if type(k) is str:
        l[i] = l[i].replace('_x000D_\n',',')
        l[i] = l[i].replace('\n',',')
        try:
            j.append(usaddress.tag(l[i])[0])
        except:
            j.append(collections.OrderedDict([('Recipient','bad')]))

new_df = pd.DataFrame(j)
# new_df.to_excel('test.xlsx')
# print(new_df.head(10))

In [149]:
len(new_df)

1020

In [ ]:
new_df['test'] =

In [158]:
(new_df['AddressNumber'] + ' ' + new_df['StreetName']).to_numpy()

array(['7005 Rain Creek', '7005 Rain Creek', '7005 Rain Creek', ...,
       '30303 Oak Tree', '30303 Oak Tree', '4041 Hidden Valley'],
      dtype=object)

In [152]:
for k in new_df:
    print(k)
    print(i)
    # print(' '.join(new_df.iloc[i][['AddressNumber', 'StreetName']]))

Recipient
AddressNumber
StreetName
StreetNamePostType
PlaceName
StateName
ZipCode
CountryName
StreetNamePreDirectional
OccupancyIdentifier
BuildingName
StreetNamePreType
OccupancyType
USPSBoxType
USPSBoxID
SubaddressType
SubaddressIdentifier
StreetNamePostDirectional

In [148]:
new_df

,Recipient,AddressNumber,StreetName,StreetNamePostType,PlaceName,StateName,ZipCode,CountryName,StreetNamePreDirectional,OccupancyIdentifier,BuildingName,StreetNamePreType,OccupancyType,USPSBoxType,USPSBoxID,SubaddressType,SubaddressIdentifier,StreetNamePostDirectional
0,Robin Romans,7005,Rain Creek,Pkwy,Austin,Texas,78759-7030,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Robin Romans,7005,Rain Creek,Pkwy,Austin,Texas,78759-7030,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Robin Romans,7005,Rain Creek,Pkwy,Austin,Texas,78759-7030,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tom Mackowski,6905,Nottoway,Lane,Lumberton,Texas,77657,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tom Mackowski,6905,Nottoway,Lane,Lumberton,Texas,77657,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,"Hanna Avdey, McGuire Moorman Hospitality, LLC",1711,Congress,Ave.,Austin,TX,78704,NaN,S.,2nd,NaN,NaN,Floor,NaN,NaN,NaN,NaN,NaN
1016,"Hanna Avdey, McGuire Moorman Hospitality, LLC",1711,Congress,Ave.,Austin,TX,78704,NaN,S.,2nd,NaN,NaN,Floor,NaN,NaN,NaN,NaN,NaN
1017,Lori Smith,30303,Oak Tree,Drive,Georgetown,Texas,78628,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1018,Lori Smith,30303,Oak Tree,Drive,Georgetown,Texas,78628,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1019,Lisa Crawley,4041,Hidden Valley,Dr.,DENISON,Texas,75020,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
j[0][0]

OrderedDict([('Recipient', 'Robin Romans'),
             ('AddressNumber', '7005'),
             ('StreetName', 'Rain Creek'),
             ('StreetNamePostType', 'Pkwy'),
             ('PlaceName', 'Austin'),
             ('StateName', 'Texas'),
             ('ZipCode', '78759-7030'),
             ('CountryName', 'United States')])

In [10]:
j[0][0].keys()

odict_keys(['Recipient', 'AddressNumber', 'StreetName', 'StreetNamePostType', 'PlaceName', 'StateName', 'ZipCode', 'CountryName'])

In [ ]:
new_df = pd.DataFrame(columns = j[0]